### ISSUE TITLE
Adjust the Dynatrace event label for Keptn evaluation to support quality gate only

### ISSUE THREAD

**Issue by robertjahn** [keptn-contrib/dynatrace-service#128]
Right now the labels are tailored for keptn using the SLO evaluation to manage deployments. For example one event reads `Promote Artifact from staging to next stage`

What I would like to see is some more generic label that is shown if you are just doing a quality gate or performance as a self service use case.  For these use case, you may just want to see a label like `SLO validation pass`, `SLO validation warn`, `SLO validation fail`

I was using this version: keptn/dynatrace-service:0.6.2

I can see the messages being in this part of the code:
https://github.com/keptn-contrib/dynatrace-service/blob/0.6.2/pkg/event_handler/cd_handler.go#L66

**Comment by grabnerandi** [comment]
Hi Rob. Please have a look at #116 - this enhancement has been available since dynatrace-service:0.7.0 and allows you to pass any meta data as labels and it will show up in dynatrace as custom properties.
0.7.0 also changed the default titles of these events to e.g: including the quality gate result score & result text
