### ISSUE TITLE
Dynatrace Service should start even if there is no dynatrace secret defined

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#201]
In its current implementation both the Dynatrace as well as the Dynatrace-SLI service are requiring a secret called "dynatrace" to be available in the keptn namespace. If this secret is not there the service will not start.
Some users dont have a dynatrace secret as they are instead using several secrets with names that reflect the name of the dynatrace tenent, e.g: dynatrace-dev, dynatrace-prod ...
As both dynatrace-xxx services are dynamically pulling the credential information from the secret that is specified in the dynatrace.conf.yaml this "startup dependency" is no longer needed

I suggest to remove the DT_TENANT and DT_API_TOKEN environment variable and also suggest to take the KEPTN_API_URL, KEPTN_API_TOKEN and KEPTN_BRIDGE_URL from a different secret, e.g: "keptn" secret where these important metrics are stored and can be referenced also from other services that need these credentials

**Comment by christian-kreuzberger-dtx** [comment]
Please consider that this is not a simple change, in fact, there are some things in dynatrace-service and dynatrace-sli-service that need to be changed drastically with this.

- [ ] Remove the code that accesses the environment variable and adapting the manifest (that's easy)
- [ ] There needs to be an automated migration step for users that use the dynatrace secret when upgrading to a new version of the service (e.g., creating/modifying dynatrace.conf to read the correct secret)
- [ ] Also, Keptn API URL+Token and Keptn Bridge URL are settings that dynatrace-service needs for integrating Dynatrace with Keptn, e.g., creating Problem notifications and backlinks in events. As of right now, these can not be fetched from Keptn, but need to be configured specifically for dynatrace-service - hence the secret and the [documentation](https://keptn.sh/docs/0.7.x/monitoring/dynatrace/install/#2-deploy-the-dynatrace-keptn-integration). Removing/changing the secret also means that there needs to be an automated migration step.
- [ ] Please consider that dynatrace-service is an execution-plane service, it does not necessarily run on the same cluster as Keptn control-plane. We need to treat this as an external service that can not access any secets/configmaps maintained by Keptn control-plane.


# Pre-requesits

Before this is implemented, I believe the following pre-requesits need to be met:

- [ ] Keptn 0.8.0 is released (any changes for Keptn 0.7.x in this context do not make sense, IMHO)
- [ ] Keptn documents a best-practice on where to store Keptn credentials for execution-plane service (e.g., in a K8s secret): API URL, Token and optionally Bridge URL (note: Keptn does not create nor maintain this secret)


# Context

I understand and support your use-case, just want to provide some context regarding the dynatrace secret.

>  Some users dont have a dynatrace secret as they are instead using several secrets with names that reflect the name of the dynatrace tenent, e.g: dynatrace-dev, dynatrace-prod ...

The secret containing dynatrace api url and token has been in place since version 0.1.0. It has been extended over time to enhance functionality, but it has not been a problem so far. 

* [0.1.2](https://github.com/keptn-contrib/dynatrace-service/blob/d65471debfdca601432ff1c85b6a17cb77954401/deploy/manifests/dynatrace-service/dynatrace-service.yaml#L16-L25)
* [0.6.0](https://github.com/keptn-contrib/dynatrace-service/blob/5eb141bc1c3822ba8f907851dddbc6b4977c5801/deploy/manifests/dynatrace-service/dynatrace-service.yaml#L34-L43)
* [0.8.0](https://github.com/keptn-contrib/dynatrace-service/blob/72d11a24357fd4d6529d9c8608b62a961698dd30/deploy/service.yaml#L118-L143)

**Comment by arthurpitman** [comment]
Fixed in #289
