### ISSUE TITLE
Triggering a remediation sequence

### ISSUE THREAD

**Issue by warber** [keptn-contrib/dynatrace-service#287]
**User Story**: As a user, I want to be able to use the *DynatraceService* to process problem events,
so that a remediation sequence can be triggered in the System.

**Details**:
The *DynatraceService* shall be capable of receiving `sh.keptn.events.problem` events and trigger a remediation sequence by sending out a `sh.keptn.event.remediation.triggered` event. 

**Definition of Done**
- [ ] *DynatraceService* is processing `sh.keptn.events.problem` events is sending out `sh.keptn.event.<stage>.remediation.triggered` events

**Comment by johannes-b** [comment]
I have concerns changing the `sh.keptn.events.problem` event to a `sh.keptn.event.problem.open`, because:
* this breaks the integration (without any gained advantage, except of the `s` in `sh.keptn.events`) and
* the Dynatrace problem notification also fires an event when the status of the problem changed - status can be: [ Open, Resolved, Closed ] Hence, it is semantically wrong when a `sh.keptn.event.problem.open` has status *Closed*  for example. 

![image](https://user-images.githubusercontent.com/729071/114546343-506acc00-9c5d-11eb-99d8-ba6753579066.png)

**Comment by christian-kreuzberger-dtx** [comment]
It was verified during https://github.com/keptn/examples/issues/165 that the changes work.
