### ISSUE TITLE
Management zones filters in dashboard not being applied in SLI definitions

### ISSUE THREAD

**Issue by drqc** [keptn-contrib/dynatrace-service#425]
Current state:
When creating an SLI/SLO quality gate based on Dashboards and using global management zones to filter the dashboard tiles, the linked SLI definitions are not being filtered.

Desired state:
When using Dynatrace dashboards the generated SLI/SLO definitions should include the general management zone filter from the dashboard.

Justification:
Reuse of existing dashboard definitions will allow rapid onboarding of new applications into quality gate framework, saving dozens of hours per application onboarding. (I have to use the manual approach and modify each query in each tile for an application dashboard and it took 6+ hours).

**Comment by arthurpitman** [comment]
In dynatrace-service 0.18.0, the issue occurs when a management zone is applied in data explorer tiles and the generated query otherwise contains no entity selector. In this instance, the management zone ID `,mz(1234...)` is being appended to the metric selector, causing a syntax error.

Proposed solution would be to more clearly separate the generation of the metric selector and the entity selector, and ensure that if a management zone is applied, it appended to the entity selector.

**Comment by arthurpitman** [comment]
@drqc, could you please verify whether this issue can still be reproduced in dynatrace-service 0.18.1?
