### ISSUE TITLE
Service onboarding only logs/updates status on status change

### ISSUE THREAD

**Issue by arthurpitman** [keptn-contrib/dynatrace-service#519]
**Current situation**
The onboarding component (responsible for adding services tagged with `keptn_managed` etc.) produces a large amount of logging every time it runs (every 60 seconds by default). Furthermore. it sends no errors to Keptn Uniform.

**Describe the solution you'd like**
The component should only log etc. when something happens or when its status changes. For example:
- when the `dynatrace` project becomes available or unavailable; without this project sync is deactivated
- when Dynatrace credentials become available or unavailable; without credentials sync cannot continue
- when Dynatrace credentials become valid or invalid; without valid credentials sync cannot continue
- when a new service is detected
- when an error onboarding a service occurs

All other "per run" logging should be set to trace.

Errors forwarded to Keptn Uniform

Ideally, Keptn Uniform would also display positive status information, i.e. notifications of when something works.

**Comment by grabnerandi** [comment]
This is great. I think this covers what I have seen as well when doing troubleshooting. What's important is that we get to see
a) when the API endpoint is incorrect, e.g: cant reach endpoint
b) when the API token is incorrect, e.g: doesnt have the right priviliges

What would also be very helpful is when an API token - that used to work - now is no longer working. This can happen if tokens rotate or if somebody accidentally deletes the token or modifies its scope in Dynatrace.
The same is true when all of a sudden the API endpoint is no longer reachable even though it was before. This can happen because of network issues

I also like the "notify if everything works as expected"

**Comment by j-poecher** [comment]
Since `dynatrace-service` has reached EOL on **December 22nd, 2023**, this issue has been closed.
